version: '3.9'

services:
  mysql:
    image: handuy1992/mysql
    restart: always
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=thisisacomplexpassword
      - MYSQL_DATABASE=obo
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=123456
    deploy:
      placement:
        constraints: [node.role == manager]
  
  obo:
    image: handuy1992/obo:latest
    restart: always
    ports:
      - 8005:8080
    depends_on:
      - mysql